---
# Source: service-a/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  namespace: "personal"
  name: "service-a"
spec:
  selector:
    app: "service-a"
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
---
# Source: service-a/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "service-a"
  namespace: "personal"
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: "service-a"
  replicas: 2
  template:
    metadata:
      name: "service-a"
      namespace: "personal"
      labels:
        app: "service-a"
    spec:
      terminationGracePeriodSeconds: 20
      containers:
        - name: "service-a"
          image: "service-a"
          imagePullPolicy: Never
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 512Mi
          env:
            - name: PORT
              value: "3000"
            - name: NODE_ENV
              value: "dev"
---
# Source: service-a/templates/deployment.yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: "service-a-autoscaler" 
  namespace: "personal"
spec:
  scaleTargetRef:
    apiVersion: apps/v1 
    kind: Deployment 
    name: "service-a" 
  minReplicas: 2
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 750
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 600
