apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.releaseName }}"
  namespace: "{{ .Values.namespace }}"
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: "{{ .Values.releaseName }}"
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      name: "{{ .Values.releaseName }}"
      namespace: "{{ .Values.namespace }}"
      labels:
        app: "{{ .Values.releaseName }}"
    spec:
      terminationGracePeriodSeconds: 20
      containers:
        - name: "{{ .Values.releaseName }}"
          image: "service-b"
          imagePullPolicy: Never
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
          env:
            - name: PORT
              value: "{{ .Values.APP.PORT }}"
            - name: NODE_ENV
              value: "{{ .Values.APP.NODE_ENV }}"

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: "{{ .Values.releaseName }}-autoscaler" 
  namespace: "{{ .Values.namespace }}"
spec:
  scaleTargetRef:
    apiVersion: apps/v1 
    kind: Deployment 
    name: "{{ .Values.releaseName }}" 
  minReplicas: {{ .Values.minReplicas }}
  maxReplicas: {{ .Values.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.averageCpuUtilization }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.averageMemoryUtilization }}

