apiVersion: v1
kind: Service
metadata:
  namespace: "{{ .Values.namespace }}"
  name: "{{ .Values.releaseName }}"
spec:
  selector:
    app: "{{ .Values.releaseName }}"
  ports:
    - protocol: TCP
      port: {{ .Values.servicePort }}
      targetPort: {{ .Values.port }}
  type: ClusterIP
